[package]
name = "swift-demangler"
version = "0.1.0"
authors = ["MACILO <maslo@rape.lol>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "^0.5"
